-- Run this in Supabase SQL Editor for your project.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  age integer,
  mobile text not null unique,
  role text not null default 'patient',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.patients (
  id bigint generated by default as identity primary key,
  name text not null,
  age text,
  condition text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.appointments (
  id bigint generated by default as identity primary key,
  patient_name text not null,
  patient_mobile text not null,
  doctor_id text not null,
  doctor_name text not null,
  doctor_specialty text,
  date text not null,
  time text not null,
  symptoms text,
  token_no integer,
  status text not null default 'booked',
  consult_type text default '',
  consult_code text default '',
  code_shared_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  appointment_id text not null,
  text text not null,
  sender_role text not null,
  sender_name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.pharmacies (
  id bigint generated by default as identity primary key,
  name text not null,
  area text,
  phone text,
  owner_email text not null unique,
  owner_password text not null,
  medicines jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.users enable row level security;
alter table public.patients enable row level security;
alter table public.appointments enable row level security;
alter table public.messages enable row level security;
alter table public.pharmacies enable row level security;

drop policy if exists "public users read/write" on public.users;
create policy "public users read/write"
on public.users
for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "public patients read/write" on public.patients;
create policy "public patients read/write"
on public.patients
for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "public appointments read/write" on public.appointments;
create policy "public appointments read/write"
on public.appointments
for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "public messages read/write" on public.messages;
create policy "public messages read/write"
on public.messages
for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "public pharmacies read/write" on public.pharmacies;
create policy "public pharmacies read/write"
on public.pharmacies
for all
to anon, authenticated
using (true)
with check (true);
